version: "3.1"

# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: it

pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 100
  entity_recognition: True
  constrain_similarities: True
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100
  constrain_similarities: True
- name: FallbackClassifier
  threshold: 0.3

policies:
- name: RulePolicy
- name: MemoizationPolicy
- name: TEDPolicy
  max_history: 5
  epochs: 100
assistant_id: 20250611-150916-senior-transfer
