version: "3.1"

# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: it

pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
  analyzer: word  # parola anziché char_wb per certe entità
  min_ngram: 1
  max_ngram: 2
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 3
  max_ngram: 5
- name: DIETClassifier
  epochs: 150
  entity_recognition: True
  constrain_similarities: True
  entity_recognition_batch_size: 64  # o un valore più alto se la RAM lo permette
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 200
  constrain_similarities: True
- name: FallbackClassifier
  threshold: 0.3


policies:
- name: RulePolicy
- name: MemoizationPolicy
- name: TEDPolicy
  max_history: 5
  epochs: 100
  # constrain_similarities: true   # → suggerito dal warning
  # ranking_length: 10
  # learning_rate: 0.001
  # batch_size: 32
assistant_id: 20250611-150916-senior-transfer
